In [4]:
import pandas as pd
import numpy as np
from sklearn import linear_model

C:\Users\mtmul\AppData\Local\Temp\ipykernel_19852\3012686526.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [6]:
df = pd.read_csv("houseprices.csv", sep="\t")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [10]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [11]:
model.coef_

array([135.78767123])

In [12]:
model.intercept_

180616.43835616432

In [14]:
model.predict([[5000]])

c:\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [15]:
import pickle

with open('model_pickle', 'wb') as f:
    pickle.dump(model, f)


In [16]:
with open("model_pickle", 'rb') as f:
    mp = pickle.load(f)

In [18]:
mp.predict([[5000]])

c:\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [21]:
import joblib

joblib.dump(model, 'model_joblib')

['model_joblib']

In [22]:
mj = joblib.load('model_joblib')

mj.predict([[5000]])

c:\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got scalar array instead:
array=5000.
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.